/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-07-01 07:04:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class postMsg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>发帖</title>\r\n");
      out.write("    <link href=\"css/main.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"css/else.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"top\">\r\n");
      out.write("    <div class=\"top_content\">\r\n");
      out.write("       <ul>\r\n");
      out.write("          <li><a href=\"register.jsp\">注册</a></li>\r\n");
      out.write("          <li><a href=\"login.jsp\">登录</a></li>\r\n");
      out.write("       </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div><!--top结束-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("   <div class=\"logo\">\r\n");
      out.write("             <img src=\"images/logo.png\" />\r\n");
      out.write("   </div><!--logo结束-->\r\n");
      out.write("   <div class=\"nav\">  \r\n");
      out.write("      <div class=\"nav_mid\">\r\n");
      out.write("         <div class=\"nav_mid_left\">\r\n");
      out.write("            <ul>\r\n");
      out.write("               <li><a href=\"index.html\" style=\"color:#FF9\">首页</a></li>\r\n");
      out.write("               <li><a href=\"ShowResList\">资源中心</a></li>\r\n");
      out.write("               <li><a href=\"ShowMsgList\">交流论坛</a></li>\r\n");
      out.write("               <li><a href=\"upload.jsp\">我要分享</a></li>\r\n");
      out.write("               <li><a href=\"userInfo.jsp\">个人信息</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"nav_mid_right\">\r\n");
      out.write("            <form action=\"\" method=\"post\">\r\n");
      out.write("               <input type=\"text\" class=\"searText\"/>\r\n");
      out.write("            </form>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div><!--nav_mid结束-->\r\n");
      out.write("   </div><!--nav结束-->  \r\n");
      out.write("    \r\n");
      out.write("   <div class=\"main\">      \r\n");
      out.write("      <div class=\"secondNav\">\r\n");
      out.write("         <ul>\r\n");
      out.write("           <li><a>全部帖子</a></li>\r\n");
      out.write("           <li><a style=\"color:#900; background-color:#FFC\">我要发帖</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"postContent\">\r\n");
      out.write("      <form action=\"addMsg.jsp\" method=\"get\">\r\n");
      out.write("          <div class=\"postFunc\">\r\n");
      out.write("            <input type=\"submit\" value=\"发送\" class=\"send\">\r\n");
      out.write("            <input type=\"button\" value=\"存草稿\" class=\"elseBtn\">\r\n");
      out.write("            <input type=\"button\" value=\"取消\" class=\"elseBtn\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"postDetail\">\r\n");
      out.write("              <label>发帖人：<input type=\"text\" class=\"postInput\" name=\"msgPoster\" placeholder=\"请输入发贴人用户名\" ></label><br/>\r\n");
      out.write("              <label>&nbsp;标题：<input type=\"text\" class=\"postInput\" name=\"msgTitle\" placeholder=\"请输入帖子主题\" ></label><br/>\r\n");
      out.write("              <label>&nbsp;时间：<input type=\"text\" class=\"postInput\" name=\"msgDate\" placeholder=\"请输入上传时间\" ></label><br/>\r\n");
      out.write("              <label>&nbsp;内容：</label><br/>\r\n");
      out.write("              <textarea class=\"postArea\" name=\"msgContent\" placeholder=\"请输入您要发布的内容\" ></textarea>\r\n");
      out.write("          </div>\r\n");
      out.write("      </form>    \r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write("   </div><!--main结束-->\r\n");
      out.write("</div><!--wrap结束-->\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <div class=\"footer_content\">\r\n");
      out.write("        <img src=\"images/footer.png\" />\r\n");
      out.write("        <br/>\r\n");
      out.write("        <span>联系方式：邮箱crystalhzr@163.com</span>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
